spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?createDatabaseIfNotExist=true
    username: root
    password: Oratoroeu@01
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379
    mail:
      host: smtp.mailtrap.io
      port: 2525
      username: 4b395f9174a95a
      password: 9b7f0e214110d7
      properties:
        mail:
          transport:
            protocol: smtp
          debug: true
          smtp:
            auth: true
            starttls:
              enable: true
  jwt:
    secret: secret